- hosts: linux
  vars:
    teams:
      - csk
      - rcb
      - mi
      - srh
  tasks:
  - name: print list variables
    debug:
      msg: "{{ teams [0] }}"
  - name: print list variables
    debug:
      msg: "{{ item }}"
    with_items:
      - "{{ teams }}"
