- hosts: linux
  tasks:
  - name: create multipole directory
    file:
      path: "{{ item }}"
      state: directory
      mode: 0775
    with_items:
    - /home/ansible/folder1
    - /home/ansible/folder2
    - /home/ansible/folder3
